name: Publicar Paquete

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Instalar dependencias
        run: npm ci

      # Paso 1: Publicar en el registro oficial de npm
      - name: Publicar en npm
        run: npm publish --access public --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Paso 2: Publicar en GitHub Packages
      - name: Publicar en GitHub Packages
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm publish --registry=https://npm.pkg.github.com/
        env:
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
=======
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 50ba5f2 (chore: update publish workflow to trigger on push and optimize registry authentication)
